### ISSUE TITLE
Updates on recommendation page

### ISSUE THREAD

**Issue by ghorawat** [gankit/plan-selector#16]
![image](https://cloud.githubusercontent.com/assets/23464741/24513103/3c5a7378-1525-11e7-8407-e7e15b98147d.png)
![plan selector](https://cloud.githubusercontent.com/assets/23464741/24513136/501467e8-1525-11e7-958f-3bd69c5a0f20.png)

**Comment by gankit** [comment]
@ghorawat This is an image. Can you just paste the text in here?

**Comment by ghorawat** [comment]
[https://docs.google.com/document/d/19kEOoaPTWeg7Y0Fx37tRnp_R4WK9pM9jBzZNdM7fvHo/edit?usp=sharing](url)

**Comment by ghorawat** [comment]
1. Relabel to : "Net Annual Price"
Your total annual premium less any contribution your employer is making toward money accounts and bonuses

	2. Expected Costs
Likely out of pocket expenses in addition to the premiums that you will incur for given expected healthcare usage

	3. Relabel to: "Savings on price"
Premium dollars saved by picking the recommended option relative to other options

To consider adding another column "Savings on Expected Costs"
Total dollars saved by picking the recommended option relative to other options

	4. Add the word "per year" at the end of the cost
Add the following text in the 'Our Recommendation' section:

We minimized the total expected costs (including premium and expected out of pocket spending) for the chosen healthcare utilization scenario. We recommend the option that minimizes costs for a given healthcare utilization. Remember that insurance is protection against the worst scenarios (even if they are not very likely - hence, we suggest that you pick the recommended plan for a 'high' utilization scenario. 

	5. Add the following text below:
Expected healthcare utilization is the expected total price (not just that you might pay) for the upcoming year. Medium is the typical spend based on age and sex. High and Low are 75th and 25th percentile values respectively. 

>> Lets start with the High value pre-selected

For later: we should do a slider with Low, Medium, High but allowing people to move the slider beyond these values too.
