### ISSUE TITLE
New Glossary page

### ISSUE THREAD

**Issue by ghorawat** [gankit/plan-selector#17]
![plan selector](https://cloud.githubusercontent.com/assets/23464741/24529589/59946458-1561-11e7-9efb-37f4a8de3d61.png)

![image](https://cloud.githubusercontent.com/assets/23464741/24529660/c1a618d4-1561-11e7-99e0-1413597b8297.png)

Lets add that link + this text on a page. At a later date, we can do smart linking where a 'learn more' icon will link to specific paragraphs in the Glossary section. 

Also - I don't particularly like the word 'Glossary' or 'Help' for this section - any other ideas? What we really want to convey is that here is where we demystify complex jargon.

**Comment by gankit** [comment]
@ghorawat Is this text from the glossary doc?

**Comment by ghorawat** [comment]
[https://docs.google.com/document/d/1DrTIw9XWtmRvZjiB6-dixTx2V8jqwd90nJ3wqseakuE/edit?usp=sharing](url)
This link has the Glossary in text. Strange that GitHub converts everything to images when I paste text.

**Comment by gankit** [comment]
Do you just want this to be a separate page? Or sprinkled throughout as tooltips?

**Comment by ghorawat** [comment]
Was thinking just a separate page for now. Ideally we should be able to jump to specific sections of the page - so later we can do some smart linking. 
Its super easy for me to mock-up the sprinkled throughout version but I was thinking it may not be needed in the MVP. Your thoughts?
