### ISSUE TITLE
Premium calculation error (rounding)

### ISSUE THREAD

**Issue by ghorawat** [gankit/plan-selector#2]
Seeing some minor differences between inputs on 'Add plan' screen vs. summary on 'Available Plans' screen.
e.g.
UHC Option 2:
Rate should be 331.67*12=3980 but its computing 3972
I think its not computing decimals at all. .67*12 = 8 => the difference seen.
As a rule we should do math at 2 decimal places (pennies) since that's how payroll etc. works.

UHC Savings plan HSA
$3380 vs. 3383.9

**Comment by gankit** [comment]
2079.96+768.04=2848
-1400-400=-1800
2848-1800=1048 (not 1028)
