### ISSUE TITLE
Minor: repeat user workflow

### ISSUE THREAD

**Issue by ghorawat** [gankit/plan-selector#20]
I may come back without clicking on my unique link in the email.
So some questions:
1. Because the site is password less, if we see the same email again - perhaps we can prompt them to use the link in their email or /and give them an option to get the email again (to be able to click on the link)

2. Do we want to add some text on the intro page on how they can pick up where they left?
Something like:
"Use the unique link that was sent to you via email if you are returning user. 
Can't find it? Enter your email again and we'll get it to you again in a jiffy"

**Comment by gankit** [comment]
Save session in a cookie
