### ISSUE TITLE
Recommendation calc issues

### ISSUE THREAD

**Issue by ghorawat** [gankit/plan-selector#4]
See attached PDF + images. **Split family cases not matching.** 
Apologies in advance for not being more descriptive - wanted to get this out before I took off.

[Algo testing.pdf](https://github.com/gankit/plan-selector/files/867079/Algo.testing.pdf)

![image](https://cloud.githubusercontent.com/assets/23464741/24282800/082ff344-101f-11e7-8a3d-267531bbde7d.png)
![image](https://cloud.githubusercontent.com/assets/23464741/24282783/f7867180-101e-11e7-8187-a7e80c82d785.png)
![image](https://cloud.githubusercontent.com/assets/23464741/24282809/125a0ba2-101f-11e7-99eb-c60162ec5369.png)

**Comment by gankit** [comment]
Fixed a bug here. Most match now.

**Comment by gankit** [comment]
@ghorawat Your calculation here seems off. From your pdf:
All on Option 1:
3522+2625+.2*(8286.49-2625)=7279.298
Off by $500 !

Isn't the deductible 3500 since its the entire family? 2625 is only the deductible for employee + children

**Comment by ghorawat** [comment]
Yup - i should have used 3500. Alls looking good now.
